# Generated by Django 3.2 on 2021-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(
                null=True,
                upload_to='users_avatar/',
                verbose_name='Аватар'),
        ),
    ]
