# Generated by Django 3.2 on 2021-04-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты'},
        ),
    ]
