# Generated by Django 3.2 on 2021-04-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cooment',
            new_name='Comment',
        ),
    ]
