# Generated by Django 3.2 on 2021-04-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_cooment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parnet',
        ),
    ]
