# Generated by Django 3.2 on 2021-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                upload_to='posts/',
                verbose_name='Картинка'),
        ),
    ]
