# Generated by Django 3.2 on 2021-04-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
