# Generated by Django 3.2 on 2021-04-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_follow_unique_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_for_post',
            field=models.ManyToManyField(
                related_name='posts', to='blog.Comment'),
        ),
    ]
