# Generated by Django 3.2 on 2021-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_comment_for_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_for_post',
            field=models.ManyToManyField(
                related_name='posts', to='blog.Comment'),
        ),
    ]
