# Generated by Django 3.2 on 2021-04-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_comment_for_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_for_post',
        ),
    ]
