# Generated by Django 3.2 on 2021-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_post_comment_for_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('user',
                     'User'),
                    ('moderator',
                     'Moderator'),
                    ('admin',
                     'Admin')],
                default='user',
                max_length=10,
                verbose_name='Роль'),
        ),
    ]
