# Generated by Django 3.2 on 2021-04-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_follower', to='blog.follow', verbose_name='Подписчики и подписки'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_like', to='blog.like', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_comment', to='blog.comment', verbose_name='Комментарии'),
        ),
    ]
