# Generated by Django 3.2 on 2021-04-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210430_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
